### ISSUE TITLE
Digitally Sign .ps1xml files

### ISSUE THREAD

**Issue by ghost** [atkinsroy/HPESimpliVity#1]
Is there any intent to digitally sign the .ps1xml files? Currently the module cannot be imported when the Execution policy is set to anything other than Unrestricted.

**Comment by atkinsroy** [comment]
Yes, thank you for reminding me. I am in the process of getting a certificate now.

**Comment by atkinsroy** [comment]
Published Version 1.1.2, which is a  signed version to the PowerShell Gallery.
