### ISSUE TITLE
ShutdownHPESimpliVityCluster.ps1 doesn't work as expected

### ISSUE THREAD

**Issue by chrileingar** [atkinsroy/HPESimpliVity#2]
When I run the Script as it is I get an Error Message **"No parameter matching the parameter name "IgnoreCertReqs"** was found.

When I remove the "-IgnoreCertReqs" Parameter in the Scripts "ShutdownHPESimpliVityCluster.ps1" and in the "HPESimpliVity.psm1" Module and reload the HPSimpiVity Modules, the error has gone but when the script continues and tries to shutdown the OVCs a new error rises up **"Runtime error: The remote server returned an error: (400) Invalid request"** but one OVC was correctly shut down, the other States online and the Script Terminator.

SimpliVity Version is: 3.7.10

**Comment by atkinsroy** [comment]
Hi Christoph, I need to retest this script to accommodate shutting down the last OVC in the environment. Please provide the requested information and I'll test and provide an update.

**Comment by atkinsroy** [comment]
Issue is resolved. The script can successfully shutdown every virtual controller in the cluster, including the last one.
