### ISSUE TITLE
Get-SVTclusterConnected is Backwards

### ISSUE THREAD

**Issue by SOM-Scott** [atkinsroy/HPESimpliVity#4]
If I run Get-SVTclusterConnected -ClusterName "Cluster-A" It will return all clusters except for Cluster-A. If I run Get-SVTclusterConnected -ClusterName "Cluster-B" It will return all clusters except for Cluster-B, including Cluster-A.

Also, would it be possible to have -ClusterName be optional so that just running Get-SVTclusterConnected will return all clusters that you are connected to?

**Comment by SOM-Scott** [comment]
Simple test:
`Get-SVTclusterConnected -ClusterName Cluster-A | Where-Object -Property ClusterName -Match Cluster-A`

**Comment by SOM-Scott** [comment]
Should have read the help

**Comment by atkinsroy** [comment]
This command is a little odd, I agree. It’s basically saying show me the clusters connected to the cluster I specify. So it doesn’t show that cluster.

Also, you really do need to specify a cluster. I thought about accepting pipeline input, but you’d see a lot of duplicates. Whichever cluster you choose, you’re seeing a “Federation wide” view of the connected clusters. 

I could default to a specific cluster name, I guess - like the first one alphabetically.

**Comment by atkinsroy** [comment]
I have implemented a "default" cluster. It will choose the first cluster in the SimpliVity Federation, alphabetically.
