### ISSUE TITLE
JDBC Connection timeout

### ISSUE THREAD

**Issue by der-thodi** [atkinsroy/HPESimpliVity#5]
Hi, I am using this module to run cyclic scripts for monitoring purposes. Lately, I have been getting timeouts like these:

```
Runtime error: Could not get JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: 
HikariPool-1 - Connection is not available, request timed out after 30000ms.
At C:\Program Files\WindowsPowerShell\Modules\HPESimpliVity\HPESimpliVity.psm1:4681 char:9
+         throw $_.Exception.Message
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Runtime error: ... after 30000ms.:String) [], RuntimeException
    + FullyQualifiedErrorId : Runtime error: Could not get JDBC Connection; nested exception is java.sql.SQLTransientC 
   onnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
```
 
I can not exactly say which comdlet causes the exceptions. Is there a way to increase the timeout? I am using version 2.1.15, but I could update if neccesary.

**Comment by der-thodi** [comment]
Upon further inspection, this occurs with one OVC only (and every time on this OVC), at the first cmdlet after Connect-SVT. I am at loss about who to ask for help with this, any idea what could be wrong on that OVC?

**Comment by atkinsroy** [comment]
So you are saying the the initial connection to the problem OVC using Connect-SVT fails, but connections to other OVC's using the same credentials works? If this is the case, I would raise a support call with HPE. Can you log into the OVC console using puTTY?

**Comment by der-thodi** [comment]
PuTTY login works, svt-federation-show works, everything else looks fine. Could you tell me if that error message is from the OVC or from your code? May help when opening a case.

**Comment by atkinsroy** [comment]
Well, it looks as though the error is coming from the Connect-SVT command.  Can you run the Connect-SVT command manually against the problem OVC, using the same credentials? I've not seen this 30 sec timeout error before - if you do get the error, that's what you should raise your case with. HPE support will support you up to using the REST API, they don't support this PowerShell module. 

If the command works manually, then its something else. When you run your code, where does it execute? Do you have access to the OVC from where you are running it? Is DNS set correctly for that OVC? Are the stored credentials right? The other thing I would do is logon to the OVC using PuTTY and have a look around. Has one of the partitions filled up with log data or anything like that?

**Comment by der-thodi** [comment]
We had run dsv-digitalvault-init on this OVC before, but did not reboot the OVC afterwards (all of this was done together with HPE support). After an OVC reboot, everything is now back to normal.
