### ISSUE TITLE
Option to rename single restored VM

### ISSUE THREAD

**Issue by DiegoDelgadoMex** [atkinsroy/HPESimpliVity#6]
Hi,
It would be great to have the option to rename a VM while doing a single VM restore from SVT. This would give some flexibility while working on scripts

**Comment by atkinsroy** [comment]
This feature has been added to V2.1.25, which will be released shortly.  You can now name a VM you are restoring. Note:

1. Only one backup can be passed; If you pass in more than one backup object, the VM for the first backup is restored with the specified name. Any subsequent backup objects are ignored and an error is displayed. 
2. If you attempt to use an existing VM name for the restore, the task will execute but fails with an appropriate message.

Other existing functionality is unchanged - i.e. multiple VMs can be restored at once, they're named after the original VMs with an added time stamp suffix to ensure uniqueness. Also, each VM is restored to the original VMs' datastore by default. If you specify a new datastore name, all restored VMs are restored there.
