### ISSUE TITLE
exception when copy to external store

### ISSUE THREAD

**Issue by engoncharov** [atkinsroy/HPESimpliVity#8]
We use Azure blob as external storage. Everything works fine with manual backups from GUI.

I tried to script the tasks.

I try to use the command:
`Copy-SvtBackup -DestinationName cloudbackup -BackupID xxx-xxx`

where **cloudbackup** is external store name.
and receive the error:
WARNING: Runtime error: Invalid or unexpected destination specified., copy failed for backup with id xxx-xxx

I tried to check and debug web session and receive the following response from api:
{"exception":"com.simplivity.rpc.common.TaskException","path":"/api/backups/035a39cb-0f0b-48e7-89fa-bf67fbb7d672/copy","extendedResponse":"Direct copy from OmniStack to any Cloudbank store, e.g. cloudbackup, not permitted.","error_code":"142","message":"Invalid or unexpected destination specified.","timestamp":"2022-09-27T10:55:49Z","status":"400"}
0

Could you help me with that error and how to fix it?

**Comment by engoncharov** [comment]
The issue is resolved. The cluster and the catalyst store had the same name. Once we created a new catalyst store the powershell get & copy is working now

**Comment by atkinsroy** [comment]
Glad to here it. Thanks for the update.
